#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2017 OpenWrt.org

START=90

start(){
    [ -d /var/log/frp ] || mkdir -p /var/log/frp
    SERVICE_DAEMONIZE=1 \
        service_start /usr/bin/frpc -c /etc/frp/frpc.ini \
            -L /var/log/frp/frpc.log --log-level=info
    [ -z "$(pgrep /usr/bin/frpc)" ] && echo "frpc starts failed!"
}

stop(){
	if [ -z "$(pgrep /usr/bin/frpc)" ]; then
		echo "frpc is not running."
	else
        service_stop /usr/bin/frpc
	fi
}
